### ISSUE TITLE
Problem on load

### ISSUE THREAD

**Issue by Jakaboii** [EnchantedP/BungeeStaffChat#3]
When I restart my bungee server, when it gets to loading the plugin it sends this to the console:
```
[22:54:59 WARN]: Exception encountered when loading plugin: BungeeStaffChat
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'reader', line 1, column 1:
reload-bsc: "&eYou have &9reload ...
expected <block end>, but found '<scalar>'
in 'reader', line 16, column 40:
... hat-prefix: "&a[&6StaffChat&a] "9
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:519) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:111) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:79) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:71) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at me.enchanted.bungeestaffchat.BungeeStaffChat.setupDiscord(BungeeStaffChat.java:102) ~[?:?]
at me.enchanted.bungeestaffchat.BungeeStaffChat.onEnable(BungeeStaffChat.java:63) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
```
any idea on how to fix it?

**Comment by Jakaboii** [comment]
Updated the plugin, it still sends this:
```
[14:18:12 WARN]: Exception encountered when loading plugin: BungeeStaffChat
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
in 'reader', line 1, column 1:
reload-bsc: "&eYou have &9reload ...
expected <block end>, but found '<scalar>'
in 'reader', line 16, column 40:
... hat-prefix: "&a[&6StaffChat&a] "9
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:519) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:111) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:79) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:71) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at me.enchanted.bungeestaffchat.BungeeStaffChat.setupDiscord(BungeeStaffChat.java:102) ~[?:?]
at me.enchanted.bungeestaffchat.BungeeStaffChat.onEnable(BungeeStaffChat.java:63) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:62c1210:118]
```

**Comment by Jakaboii** [comment]
Found out it was just because there was a "9" after the Speech marks
